---
jenkins_jobs: ["containers-containerd-upstream-integration-tests-openSUSE-Factory-btrfs-devel","storage-qa-teuthology-smoke-devel-6.0", "manager-3.1-cucumber", "manager-Head-cucumber", "storage-teuthology-suite"]
